## Deep Learning with PyTorch: A 60 Minute Blitz

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[ 3.1748e-29,  4.5565e-41,  3.5780e-37],
        [ 0.0000e+00,  1.4013e-45,  9.8091e-45],
        [ 3.5780e-37,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  4.7428e+30],
        [ 4.6172e+24,  3.5193e+36,  4.7615e+30]])


Construct a random matrix

In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.1308,  0.9330,  0.5734],
        [ 0.7228,  0.6273,  0.0368],
        [ 0.0405,  0.8001,  0.4565],
        [ 0.3058,  0.9978,  0.7540],
        [ 0.5581,  0.2287,  0.5842]])


Construct a matrix filled zeros and of dtype long:

In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


Construct a tensor directly from data:

In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


Create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [12]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

# Get size
print(x.size())

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[-2.2046, -0.2455, -1.6797],
        [-0.6099, -0.3626,  1.1034],
        [-0.7141,  0.5715, -2.4977],
        [-0.2357,  0.4099,  0.6898],
        [-1.0437,  1.0009,  0.2159]])
torch.Size([5, 3])


### Operations
#### Addition

In [18]:
# syntax 1
y = torch.rand(5, 3)
print(y)
print(x + y)

tensor([[ 0.7746,  0.0039,  0.3318],
        [ 0.2129,  0.0159,  0.7628],
        [ 0.1060,  0.2681,  0.3527],
        [ 0.8035,  0.2275,  0.2569],
        [ 0.6235,  0.4492,  0.8959]])
tensor([[-1.4300, -0.2416, -1.3479],
        [-0.3970, -0.3467,  1.8662],
        [-0.6081,  0.8396, -2.1450],
        [ 0.5678,  0.6374,  0.9467],
        [-0.4201,  1.4500,  1.1118]])


In [20]:
# syntax 2
print(torch.add(x, y))

tensor([[-1.4300, -0.2416, -1.3479],
        [-0.3970, -0.3467,  1.8662],
        [-0.6081,  0.8396, -2.1450],
        [ 0.5678,  0.6374,  0.9467],
        [-0.4201,  1.4500,  1.1118]])


In [21]:
# Provide output tensor
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.4300, -0.2416, -1.3479],
        [-0.3970, -0.3467,  1.8662],
        [-0.6081,  0.8396, -2.1450],
        [ 0.5678,  0.6374,  0.9467],
        [-0.4201,  1.4500,  1.1118]])


In [22]:
# Addition in place
y.add_(x)
print(y)

tensor([[-1.4300, -0.2416, -1.3479],
        [-0.3970, -0.3467,  1.8662],
        [-0.6081,  0.8396, -2.1450],
        [ 0.5678,  0.6374,  0.9467],
        [-0.4201,  1.4500,  1.1118]])


In [31]:
# Use NumPy style slicing
print(x[:, 1])
print(x.shape)
print(x.size())
assert x.shape == x.size()

tensor([-0.2455, -0.3626,  0.5715,  0.4099,  1.0009])
torch.Size([5, 3])
torch.Size([5, 3])


#### Resizeing

In [34]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use .item() to get the value as a Python number

In [35]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([ 0.5519])
0.551888108253479


### NumPy bridge

In [37]:
# Torch tensor to Numpy
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([ 1.,  1.,  1.,  1.,  1.])
[1. 1. 1. 1. 1.]


In [39]:
# Note that b is a remaping of a, so b changes with a.
a.add_(1)
print(a)
print(b)

tensor([ 3.,  3.,  3.,  3.,  3.])
[3. 3. 3. 3. 3.]


In [41]:
# Numpy to Torch
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
print('')

np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


### Cuda tensors

In [18]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([ 2.5240], device='cuda:0')
tensor([ 2.5240], dtype=torch.float64)
